# permissions for end users to view opsovereasies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsovereasy-viewer-role
rules:
- apiGroups:
  - operators-over-ez.mydomain.com
  resources:
  - opsovereasies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators-over-ez.mydomain.com
  resources:
  - opsovereasies/status
  verbs:
  - get
